### PR TITLE
ADCS (MS AD-PKI) plugin

### PR DESCRIPTION
**Pull request by sirferl**
Right before Xmas I polished the home breed plugin an integrated it.

This adds issuing and sourcing capabilities for the Mcrosoft AD based ADCS PKI.
It's based on [certsrv](https://github.com/magnuswatn/certsrv), which does all the communication.
For this to work, the web interface of the ADCS server has to be enabled.

You create a CA in lemur and use it for creating the certificates.
Care should be taken with the template. MS uses the names displayed in the cert-plugin without spaces.
The id of the new cert is returned.
The source plugin searches for "TLS Server" certificates in the id range specified by ADCS_START and ADCS_STOP. If there are not as many IDs as ADCS_STOP, the plugin stops at the last cert.
No endpoints are retrieved, which leads to a warning when synchronizing.

Just add the following configuration to the lemur.conf.py

ADCS_SERVER = "FQDN of your ADCS Server"
ADCS_AUTH_METHOD = "The chosen authentication method. Either ‘basic’ (the default), ‘ntlm’ or ‘cert’ (SSL client certificate). The next 2 variables are interpreted differently for different methods."
ADCS_USER =  "The username (basic) or the path to the public cert (cert) of the user accessing PKI"
ADCS_PWD = "The passwd (basic) or the path to the private key (cert) of the user accessing PKI"
ADCS_TEMPLATE = "Template to be used for certificate issuing. Usually display name w/o spaces"
ADCS_START = <number that gives the start id for source-plugin.>
ADCS_STOP = <number that gives the highest id to search for>
ADCS_ISSUING = "contains the issuing cert of the CA"
ADCS_ROOT = "contains the root cert of the CA"

Please try it out.
regards
sirferl

### CODE REVIEW

**Comment by castrapel** [comment]
Hmm, it looks like there are some lint errors. Can you try to run "make lint" locally and resolve them? PyCharm and other IDEs have functionality built in that can automatically reformat lines and resolve common lint errors as well.

**Comment by sirferl** [comment]
ok, sorry, I will do that after the holidays...
sirferl

**Comment by sirferl** [comment]
Hm, checks are not performed automatically since last master merge ?
Is there anything I missed?

**Comment by mikejhathaway** [comment]
Hi,

I have just installed Lemur and it seems that the ADCS plugin was not installed by default and is not in the lemur/plugins folder, how do I get this installed?

Thanks

Mike

**Comment by sirferl** [comment]
It's not merged in the main branch yet, so you have to use my fork.
I hope the guys from netflix will merge it anytime soon.
regards
ferdinand

**Comment by mikejhathaway** [comment]
Ah, Ok. Can you direct me to it please?

Sorry, newbie here :-)

**Comment by mikejhathaway** [comment]
Ignore that I found it...

However when I try and make a release, the following error is thrown:

Could not find a version that satisfies the requirement kombu==4.2.2 (from lemur==0.7.0) (from versions: 0.1.0 ......4.2.2.post1)
No matching distribution found for kombu==4.2.2 (from lemur==0.7.0)

Will do some poking around but thought to see if you or anyone else had encountered this??

Thanks

Mike

**Comment by castrapel** [comment]
Sorry for the delay here! Thanks for this PR, will merge it now.

**Comment by vovaled** [comment]
ADCS_ISSUING = "contains the issuing cert of the CA"
ADCS_ROOT = "contains the root cert of the CA"

What format I should use here? 

I get this error:
  File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1140, in load_pem_x509_certificate
    raise ValueError("Unable to load certificate")
ValueError: Unable to load certificate

**Comment by sirferl** [comment]
Hi vovaled,
Iuse standard .pem format
regards

**Comment by vovaled** [comment]
Tried path:
ADCS_ISSUING = "/path/to_file/crt.pem"

tried: 
ADCS_ISSUING = "-----BEGIN CERTIFICATE-----
MIIFSDCCBDCg........................................
-----END CERTIFICATE-----"

Both not working for me.
File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1140, in load_pem_x509_certificate
raise ValueError("Unable to load certificate")
ValueError: Unable to load certificate

**Comment by sirferl** [comment]
Hello @vovaled : 
This has to be python-Syntax.
You have to use three quotation marks at the beginning and at the end of the block like this:
ADCS_ISSUING = """-----BEGIN CERTIFICATE-----
MIIFSDCCBDCg........................................
-----END CERTIFICATE-----"""

**Comment by vovaled** [comment]
Thank you

**Comment by nimbius** [comment]
does this plugin have support for a policy CA?  I keep getting a certificate check failure due to a missing chain cert for my policy CA.

can I add this policy CA somewhere?

**Comment by nimbius** [comment]
with basic authentication I keep getting 401 unauthorized for my user/pw.  is there some special formatting required here?

**Comment by sirferl** [comment]
> with basic authentication I keep getting 401 unauthorized for my user/pw. is there some special formatting required here?

Hi @nimbius 
No, just a string in quotes.
regards
ferdinand

**Pull request merged**
