### PR TITLE
[WIP] Automation scripts

### PR DESCRIPTION
**Pull request by jeremy-h**
this is a bit WIP

adding a manage.py command to create a certificate from the command line.  It is a butchering of ProvisionELB.

### CODE REVIEW

**Comment by kevgliss** [comment]
When you're ready, please squash this PR down into one or a few commits.

**Comment by jeremy-h** [comment]
squashed, but screwed up the commit messages.

**Comment by kevgliss** [comment]
Can you re-base? This looks good to merge otherwise.

**Comment by kevgliss** [comment]
Still can't re-base :-(

**Comment by kevgliss** [comment]
Feel free to re-open.

**Pull request closed without merging**
