### PR TITLE
Use special issuer values <selfsigned> and <unknown> in special cases

### PR DESCRIPTION
**Pull request by intgr**
This way it's easy to find/distinguish selfsigned certificates stored in Lemur.

### CODE REVIEW

**Comment by intgr** [comment]
Also, note that the code in `utils.py` `check_cert_signature` will be re-used in PR #1514 -- I will work on that too at one point.

**Comment by intgr** [comment]
OK rebased, this is now ready for merging.

**Comment by intgr** [comment]
Rebased & resolved the conflict.

**Comment by intgr** [comment]
Rebased, conflicts resolved.

**Comment by hosseinsh** [comment]
Hi Marti, thanks for the PR. Just merged it.

**Pull request merged**
