### PR TITLE
Add DIGICERT_ORDER_TYPE to Digicert plugin

### PR DESCRIPTION
**Pull request by jchuong**
This allows lemur.conf.py to control which kind of certificate to
order.  User defined options are not currently supported in the the UI,
so we cannot create multiple Digicert authorities at runtime for
separate certificate types.

### CODE REVIEW

**Comment by jchuong** [comment]
You can see valid types with the API documentation here https://www.digicert.com/services/v2/documentation/order/overview-submit

**Comment by kevgliss** [comment]
Can you add what this variable does to the docs? http://lemur.readthedocs.io/en/latest/administration.html?highlight=digicert#digicert-issuer-plugin

**Comment by jchuong** [comment]
@kevgliss ping, I've updated the doc for this variable.

**Comment by kevgliss** [comment]
lgtm, thanks!

**Pull request merged**
