### PR TITLE
Azure-Dest: Switch to PCKS12 upload

### PR DESCRIPTION
**Pull request by sirferl**
Azure keyvault accepts PEM and PKCS12-Format Certificates - only the latter is usable for Azure Application Gateway.
Therefore we upload in PKCS12 format instead of PEM.

### CODE REVIEW

**Comment by hosseinsh** [comment]
@sirferl thanks for raising this PR. Btw, any chance you might be able to add any tests?

**Comment by sirferl** [comment]
@hosseinsh Hi, I added a unit Test. But I have a problem to get it to work. I tried the same approach as in the Digicert-Plugin-Test to mimick the POST to the Azure-Vault but the call is always performed with the requests -library. Could you have a look at it, please?

**Comment by hosseinsh** [comment]
Hey @sirferl, sorry work has been busy these days. 
A quick glance a the [Travis CI](https://app.travis-ci.com/github/Netflix/lemur/jobs/526799473#L1710-L1717) points to:

```
_______________________ TestAzureDestination.test_upload _______________________
Traceback (most recent call last):
  File "/home/travis/build/Netflix/lemur/lemur/plugins/lemur_azure_dest/tests/test_azure_dest.py", line 137, in test_upload
    iferl = subject.upload(name, body, private_key, cert_chain, options)
  File "/home/travis/build/Netflix/lemur/lemur/plugins/lemur_azure_dest/plugin.py", line 163, in upload
    cert_p12 = serialization.pkcs12.serialize_key_and_certificates(
AttributeError: module 'cryptography.hazmat.primitives.serialization' has no attribute 'pkcs12'
=============================== warnings summary ===============================
```
hope that helps.

Btw, `make test` is helpful to run the tests locally, and debug.

**Comment by sirferl** [comment]
Hi, @hosseinsh sorry that I wasted your time. I corrected the obvious error and now the system shows the behaviour I am not able to fix. The request shown in the log is not performed by the mock-request-machinery like intended and therefore fails. As a consequence the response assignmnet fails.

**Comment by hosseinsh** [comment]
No worries, @sirferl, I will try to take a look next week.

**Comment by hosseinsh** [comment]
debugging:

accessing via mock would work
```
subject.session.post('mock://couldbeanyvalue.com/certificates/localhost/import?api-version=7.1', headers={}, json={}).status_code
```

but not via https:
```
subject.session.post('https://couldbeanyvalue.com/certificates/localhost/import?api-version=7.1', headers={}, json={}).status_code
```

which triggered this error:
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='couldbeanyvalue.com', port=443): Max retries exceeded with url: /certificates/localhost/import?api-version=7.1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x108def2d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

took some time to try and error and read online, but [this](https://requests-mock.readthedocs.io/en/latest/adapter.html?highlight=mount#creating-an-adapter) became handy. I suppose the Azure destination enforces the `https` in the URL, which  caused this error.

**Review by hosseinsh — APPROVED** [review]

**Comment by hosseinsh** [comment]
Thanks again for the PR @sirferl and being supportive with adding tests.

**Comment by sirferl** [comment]
@hosseinsh thank you for sorting this out. I learned a lot as usual...and there is more to come.

**Pull request merged**
