### PR TITLE
CSR Export Plugin

### PR DESCRIPTION
**Pull request by jchuong**
This plugin allows a certificate to be exported as a CSR via OpenSSL
x509.  The workflow will be:
* Create self-signed cert via Cryptography authority
* Export CSR via this plugin
* Sign your own cert outside of Lemur
* Import new cert with private key

### CODE REVIEW

**Comment by jchuong** [comment]
For #987 but you have to create the self-signed first, then import the actual cert.

**Comment by kevgliss** [comment]
This looks good, although I am working on the use-case for this? Generally speaking, I'd expect that Lemur be directly integrated with the CA itself. That way the user doesn't have to handle key material. Are there CA's out there that a purely manual and have no APIs at all?

**Comment by jchuong** [comment]
I also prefer having Lemur request the cert from the CA itself.  There are two cases why you may want CSR however.

1.  I work at a third party company that serves traffic for a customer website (eg Akamai, Fastly, other CDNs).  A new customer wants a third party that we don't support in Lemur, because of reasons (maybe they negotiated some kind of deal, or prefer one over the other).  Then we can give the customer the CSR, and we keep the key to ourselves.  The customer gets the certificate from our CSR and we just import it back into Lemur.  

Downside is the person creating the CSR has to copy the private key into the newly imported certificate (and remove the original).  I have a change that also copies the original key, so the user doesn't have to do that (just use replaces field).

2. The CA doesn't have an API (or we just want to do a one-off with this CA, or can't create the plugin quickly enough or something).

**Comment by kevgliss** [comment]
Interesting, thanks for the insight!

**Pull request merged**
