### PR TITLE
Optimize certificates sql

### PR DESCRIPTION
**Pull request by ilyalabun**
This change gave us 20-30% page load time decrease when searching by certificate name and/or cn

### CODE REVIEW

**Comment by ilyalabun** [comment]
Hi @hosseinsh! Do you have any comments on this? Just out of curiosity -- is this PR OK to be merged or it needs some amendments to be made?

**Comment by hosseinsh** [comment]
hey @ilyalabun, thanks for your PR and sorry for how long it took us to review and merge it. 
I did so local testing, and could see similar performance gains, if not more!

**Comment by ilyalabun** [comment]
Hi @hosseinsh, thanks for testing and merging it!

**Comment by jramosf** [comment]
That's nice to hear @hosseinsh !  👍

**Pull request merged**
