### PR TITLE
adding generic OAuth2 provider

### PR DESCRIPTION
**Pull request by nevins-b**

### CODE REVIEW

**Comment by kevgliss** [comment]
Could you also add some documentation about okta? It looks very much like vanilla oauth2, perhaps highlight differences (if any?)

**Comment by nevins-b** [comment]
Sure thing! I think it is basically the vanilla oauth2 so if it makes more sense renaming this something more generic I'd be fine with that.

**Comment by kevgliss** [comment]
Yeah, perhaps renaming it simple oauth2 would be best.

**Comment by kevgliss** [comment]
Awesome, thanks!

**Pull request merged**
