### PR TITLE
Updated apache config in documentation

### PR DESCRIPTION
**Pull request by csv7**
You guys asked for one that worked... It took me a little while to tweak, esp. since I'm not a guru with python.  The comment about needing mod_wsgi isn't true, unless you want to run lemur as a cgi program... I suspect that's from an older version that ran as cgi and not as a standalone webserver.

### CODE REVIEW

**Comment by kevgliss** [comment]
Thanks, if you're pretty confident perhaps we should remove the note about it being incomplete?

**Comment by csv7** [comment]
I think it'd be ok to remove. I don't see where mod_wsgi is needed -- unless I'm missing something completely unobvious. We're running a similar python application -- Internet2's FileLocker https://sourceforge.net/projects/filelocker2/  -- which I had to tweak heavily to get it to work "just right" in our environment... Since both of them are stand-alone webservers (filelocker uses cherryPi), I used it's apache proxy config as a starting point. We've been running it for almost a year.

**Comment by csv7** [comment]
I'm going to try my hand at making a couple of plugins for Lemur... I've been using a home-grown solution to nmap our network on known ports and import ssl certs into a database and try to keep up with it... but maintaining that codebase sucks. openssl coding is the devil. Also, I need some way of automating making Internet2 Incommon certs, and Lemur could do it with a little help.

**Comment by kevgliss** [comment]
Cool, I think an Nmap source plugin could be cool... we have traditionally kept that functionality out of Lemur and had other applications handle scanning infrastructure. But given your use case, a sync plugin would fit the bill.

**Pull request merged**
