### PR TITLE
UI adjustments for mutually exclusive (checkbox version) encipher/decipher-only Key Usage

### PR DESCRIPTION
**Pull request by neilschelly**
UI adjustments to make Key Agreement, Encipher Only, and Decipher Only relationship more user-friendly. This contributes the UI half of issue #663.

### CODE REVIEW

**Comment by kevgliss** [comment]
If we want to allow for mutual exclusivity wouldn't a radio button be better here instead of forcing checkboxes to be disabled?

**Comment by neilschelly** [comment]
I could take a stab at that.

**Comment by neilschelly** [comment]
The backend validation/schema stuff for this actually got wrapped into the work at https://github.com/Netflix/lemur/pull/666 just because the entirety of handling input got refactored there.

**Comment by kevgliss** [comment]
The only work left on this would be if we decided to use radio buttons instead of checkboxes... did you want me to merge this in for you to tackle that (if you want) with another PR?

**Comment by neilschelly** [comment]
I played with radio buttons a bit. It's complicated in a variable naming context since those wouldn't "look" like all the other extension checkboxes in the data that comes back to the backend. That could be massaged from the radio buttons in Angular JS so that it still reaches the backend "looking" like it came from checkboxes to keep that consistent? Maybe consistent isn't that important, but if not, that's changing the API call inputs too.

I also had trouble with unchecking the radio buttons. A certificate can have neither of these options checked, but a radio button implies at least one of them will be checked. I'm sure it could be done by someone more familiar with Angular and/or JS, but I was unable to do it after an hour of playing. I opted to focus on the functional code contributions first, and I planned to revisit this later.

**Comment by neilschelly** [comment]
I propose rejecting this PR in favor of https://github.com/Netflix/lemur/pull/692. That version accomplishes the same thing with radio buttons.

**Comment by kevgliss** [comment]
Agreed, radio buttons do feel a lot nicer. Thanks!

**Pull request closed without merging**
