### PR TITLE
Upgrade package requests

### PR DESCRIPTION
**Pull request by titouanc**
https://github.com/shazow/urllib3/pull/1246 has been merged

The older requests version currently in master conflicts with the one required by InfluxDB, which I use in https://github.com/titouanc/lemur-influxdb

### CODE REVIEW

**Comment by kevgliss** [comment]
So it looks like it was merged, do you know if it's been released? According to: https://pypi.python.org/pypi/urllib3/1.22 they haven't released since last year 👎 

Unfortunately we have some production systems relying on mTLS support and without the fix being released we would be in a bad state.

**Comment by kevgliss** [comment]
Additionally would you like for your plugin to be included on http://lemur.readthedocs.io/en/latest/administration.html#rd-party-plugins ? If so feel free to submit a PR.

**Comment by titouanc** [comment]
You're right, I only paid attention to the PR itself as said in the comment. Sorry :disappointed: 

I will downgrade the influxdb requirement in my plugin instead, and open another PR here to reference the plugin in 3rd parties. Closing this one for now.

**Comment by kevgliss** [comment]
Yeah, it really sucks. :-(

**Pull request closed without merging**
